#!/bin/sh

# Using a 'cat' here document, create a file for jekyll
# website containing what's required for tag pages.

# Pass in tag name(s)
#   ./createtag linux bsd

CMDLINEPARAM=1     #  Takes at least one param.
TAGDIR="blog"
fileName=$(date +"%Y-%m-%d-%U")
date=$(date +"%FT%T")
update=$(date +"%Y-%m-%d %H:%M")
journal=$(date +"%a, %b %d, %y")

if [ $# -ge $CMDLINEPARAM ]
then
  blog=$@
else
  echo "Atleast ${CMDLINEPARAM} blog name is required."
  exit 1
fi

if [ -d "${TAGDIR}" ]; then

  echo "Creating journal(s) for ${blog}"

  for journal in ${blog}; do
    echo "Title for $blog:" 
    read  title 
    echo "author name is:"
    read authors
  # Cannot indent here string.
cat <<EOF >"${TAGDIR}/${fileName}th-${blog}.md"
---
title: "${title}"
slug: ${fileName}th-${blog}
authors: ${authors}
created: ${date} +0900
updated: ${update}
---

## 


EOF

echo "  - ${docs}" >> sitemap.yml

  done

else
  echo "Directory ${docs} doesn't exist or you are not in the top-level directory."
  echo "Please run again from the root directory of your project."
  exit 1
fi

exit
